# Generated by Django 4.0.4 on 2022-05-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='商品名')),
                ('price', models.IntegerField(default='', verbose_name='価格')),
                ('image_link', models.TextField(default='', verbose_name='画像リンク')),
            ],
        ),
    ]
