# Generated by Django 4.0.4 on 2022-06-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikaku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default='', verbose_name='価格')),
                ('shop', models.CharField(default='', max_length=100, verbose_name='販売店')),
                ('shop_link', models.TextField(default='', verbose_name='ショップリンク')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikaku.productmodel')),
            ],
        ),
    ]
